"""Stamps: organic shapes precomputed once, placed fast.

Physical pattern formation is slow; looking it up is not. The library holds

* **phase-separation tiles** (:func:`phase_tiles`): Cahn-Hilliard films quenched at a range
  of compositions, periodic, 256 x 256. Thresholded at 0 they are the shapes of evaporated
  metal near percolation: round droplets at low coverage, worms and a labyrinth at half,
  a film with holes above. Coverage `COVERAGES[j]` for tile family j.
:func:`field` places the tiles over the plane: each cell of a lattice (`cell_um`) takes its
own tile, one of eight rotations / mirrors and an offset, and neighbouring cells are
blended with sharpened weights, so there is no repeat and no seam. Everything is a
function of (seed, x, y): world-locked, and the same at every magnification.

The tiles are generated on first use and cached (``~/.cache/de_twin`` or
``DE_TWIN_CACHE``), a few seconds once.
"""

from __future__ import annotations

import functools
import math
import os
from pathlib import Path

import numpy as np

try:
    import numba as nb

    AVAILABLE = True
except Exception:  # noqa: BLE001
    nb = None
    AVAILABLE = False

TILE = 256
#: Cahn-Hilliard mean compositions and the coverage (fraction > 0) each gives.
MEANS = (-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5)
VARIANTS = 4  # tiles per composition
#: Pattern period (tile pixels) of the Cahn-Hilliard tiles: the island spacing is TILE /
#: ~this many islands across; see `PERIOD_PX`.
CH_EPS = 1.5
_VERSION = 4


def _cache_dir() -> Path:
    d = Path(os.environ.get("DE_TWIN_CACHE", Path.home() / ".cache" / "de_twin"))
    d.mkdir(parents=True, exist_ok=True)
    return d


def cahn_hilliard(n: int, mean: float, seed: int, eps: float = CH_EPS, steps: int = 450, dt: float = 0.5) -> np.ndarray:
    """dc/dt = lap(c^3 - c - eps^2 lap c) on an n x n torus (semi-implicit spectral)."""
    rng = np.random.default_rng(seed)
    c = mean + 0.05 * rng.standard_normal((n, n))
    k = 2 * np.pi * np.fft.fftfreq(n)
    k2 = k[:, None] ** 2 + k[None, :] ** 2
    denom = 1.0 + dt * (eps ** 2 * k2 ** 2 + 2.0 * k2)
    ch = np.fft.fft2(c)
    for _ in range(steps):
        c = np.real(np.fft.ifft2(ch))
        ch = (ch - dt * k2 * np.fft.fft2(c ** 3 - 3.0 * c)) / denom
    return np.real(np.fft.ifft2(ch))


#: The shipped tiles (8-bit signed distances, generated by :func:`generate_phase_tiles`).
PACKAGED = Path(__file__).with_name("data") / "phase_tiles.npz"
_Q = 16.0  # the signed distance (tile pixels) is kept within [-_Q, _Q]


def signed_distance(tile: np.ndarray) -> np.ndarray:
    """Periodic signed distance (tile pixels) to the edge of the tile's > 0 phase: positive
    inside it. Thresholding it at -d dilates the phase by d (erodes for +d) with the same
    topology: channels thin continuously as coverage rises."""
    from scipy import ndimage

    n = tile.shape[0]
    big = np.tile(tile > 0, (3, 3))
    inside = ndimage.distance_transform_edt(big)[n:2 * n, n:2 * n]
    outside = ndimage.distance_transform_edt(~big)[n:2 * n, n:2 * n]
    return np.where(tile > 0, inside - 0.5, 0.5 - outside)


def generate_phase_tiles() -> np.ndarray:
    """All the Cahn-Hilliard tiles (a few minutes; the package ships them)."""
    tiles = np.empty((len(MEANS), VARIANTS, TILE, TILE), np.float32)
    for i, m in enumerate(MEANS):
        for v in range(VARIANTS):
            tiles[i, v] = cahn_hilliard(TILE, m, 1000 * i + v)
    return tiles


def save_phase_tiles(tiles: np.ndarray, path: Path = PACKAGED) -> None:
    """Store the tiles as 8-bit signed distances."""
    path.parent.mkdir(parents=True, exist_ok=True)
    sd = np.stack([np.stack([signed_distance(t) for t in fam]) for fam in tiles])
    q = np.clip(np.rint((sd + _Q) / (2 * _Q) * 255.0), 0, 255).astype(np.uint8)
    np.savez_compressed(path, tiles=q, means=np.array(MEANS), version=_VERSION)


@functools.lru_cache(maxsize=1)
def phase_tiles() -> tuple[np.ndarray, np.ndarray]:
    """(tiles (len(MEANS), VARIANTS, TILE, TILE) float32, coverage per composition)."""
    path = PACKAGED
    if not path.exists():
        path = _cache_dir() / f"stamps_phase_v{_VERSION}.npz"
        if not path.exists():
            save_phase_tiles(generate_phase_tiles(), path)
    with np.load(path) as z:
        tiles = (z["tiles"].astype(np.float32) / 255.0 * (2 * _Q) - _Q).astype(np.float32)
    coverage = (tiles > 0).mean(axis=(1, 2, 3)).astype(np.float64)
    return np.ascontiguousarray(tiles), coverage


#: Up to this coverage the shapes follow the composition (droplets merging into worms);
#: above it the half-coverage labyrinth dilates (an evaporated film past percolation keeps
#: its channels, thinning), and below the first droplet family the droplets shrink.
LABYRINTH = 0.5
_LEVELS = 17
_OFFSETS = np.linspace(-_Q + 0.5, _Q - 0.5, 129)


@functools.lru_cache(maxsize=1)
def _coverage_table():
    """(levels, coverage[level, offset]): the coverage the sampler itself gives (blended
    cells, interpolation and all) at each family level, thresholded at -offset."""
    tiles, cov = phase_tiles()
    half = int(np.argmin(np.abs(cov - LABYRINTH)))
    levels = np.linspace(1.0, float(half), _LEVELS)
    path = _cache_dir() / f"stamps_coverage_v{_VERSION}_{_LEVELS}_{_OFFSETS.size}.npz"
    if path.exists():
        with np.load(path) as z:
            return levels, z["table"]
    n = 192  # a patch 16 cells across, sampled a little finer than a feature
    g = (np.arange(n) + 0.5) * (16.0 * 12.0 / n)
    X, Y = np.meshgrid(g, g)
    x, y = X.ravel(), Y.ravel()
    px_per_um = period_px_cached()  # feature = 1
    table = np.empty((_LEVELS, _OFFSETS.size))
    out = np.empty(x.size)
    for a, lv in enumerate(levels):
        _field_nb(x, y, np.full(x.size, lv), out, tiles, np.uint64(12345 + a), px_per_um, 1.0 / 12.0, 6.0)
        fs = np.sort(out)
        table[a] = 1.0 - np.searchsorted(fs, -_OFFSETS, side="right") / fs.size
    np.savez_compressed(path, table=table)
    return levels, table


def _level_offset(c: np.ndarray):
    """The family level and threshold offset that give coverage `c` per pixel."""
    tiles, cov = phase_tiles()
    half = int(np.argmin(np.abs(cov - LABYRINTH)))
    levels, table = _coverage_table()
    lv = np.interp(np.clip(c, cov[1], cov[half]), cov[1:half + 1], np.arange(1, half + 1, dtype=np.float64))
    row = np.clip(np.rint((lv - 1.0) / (half - 1.0) * (_LEVELS - 1)).astype(np.int64), 0, _LEVELS - 1)
    off = np.empty_like(c)
    # each row's pixels as one slice of a (radix) sort, not a mask over all of them per row
    order = np.argsort(row.astype(np.uint8), kind="stable")
    cuts = np.searchsorted(row[order], np.arange(_LEVELS + 1))
    cs = c[order]
    for r in range(_LEVELS):
        a, b = cuts[r], cuts[r + 1]
        if b > a:
            off[order[a:b]] = np.interp(cs[a:b], table[r], _OFFSETS)
    return levels[row], off


def period_px() -> float:
    """The mean spacing of features in a Cahn-Hilliard tile, pixels (from the structure
    factor's peak of the half-coverage tiles)."""
    tiles, _ = phase_tiles()
    t = np.tanh(tiles[MEANS.index(0.0)] / 2.0)
    S = np.mean([np.abs(np.fft.fft2(v)) ** 2 for v in t], axis=0)
    k = np.hypot(*np.meshgrid(np.fft.fftfreq(TILE), np.fft.fftfreq(TILE)))
    kb = np.round(k * TILE).astype(int)
    radial = np.bincount(kb.ravel(), S.ravel()) / np.maximum(np.bincount(kb.ravel()), 1)
    radial[:2] = 0
    return TILE / float(np.argmax(radial))


# ------------------------------------------------------------------ placement
def _hash(seed, i, j):
    z = (np.uint64(seed) ^ (np.uint64(i) * np.uint64(0x9E3779B97F4A7C15))
         ^ (np.uint64(j) * np.uint64(0xC2B2AE3D27D4EB4F))) + np.uint64(0x9E3779B97F4A7C15)
    z = (z ^ (z >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    z = (z ^ (z >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return z ^ (z >> np.uint64(31))


def _njit(**kw):
    if not AVAILABLE:
        return lambda f: f
    return nb.njit(cache=True, fastmath=True, nogil=True, **kw)


_prange = nb.prange if AVAILABLE else range
_hash_nb = _njit()(_hash) if AVAILABLE else _hash


@_njit()
def _lookup(tile, u, v):
    """Bilinear, periodic lookup in one tile at tile-pixel coordinates."""
    n = tile.shape[0]
    fu, fv = math.floor(u), math.floor(v)
    tu, tv = u - fu, v - fv
    i0 = int(fu) % n
    j0 = int(fv) % n
    i1 = (i0 + 1) % n
    j1 = (j0 + 1) % n
    a = tile[j0, i0] + (tile[j0, i1] - tile[j0, i0]) * tu
    b = tile[j1, i0] + (tile[j1, i1] - tile[j1, i0]) * tu
    return a + (b - a) * tv


@_njit(parallel=True)
def _field_nb(x, y, level, out, tiles, seed, px_per_um, cells_per_um, sharp):
    nlev = tiles.shape[0]
    nvar = tiles.shape[1]
    for k in _prange(x.size):
        cx = x[k] * cells_per_um
        cy = y[k] * cells_per_um
        ci = math.floor(cx - 0.5)
        cj = math.floor(cy - 0.5)
        fx = cx - 0.5 - ci
        fy = cy - 0.5 - cj
        # the two composition families either side of this pixel's level
        lv = min(max(level[k], 0.0), nlev - 1.0)
        l0 = int(math.floor(lv))
        l1 = min(l0 + 1, nlev - 1)
        tl = lv - l0
        acc = 0.0
        wsum = 0.0
        for dj in range(2):
            for di in range(2):
                w = (fx if di else 1.0 - fx) * (fy if dj else 1.0 - fy)
                w = w ** sharp
                h = _hash_nb(seed, ci + di, cj + dj)
                var = int(h % np.uint64(nvar))
                d8 = int((h >> np.uint64(8)) % np.uint64(8))
                ou = float((h >> np.uint64(16)) & np.uint64(0xFFFF)) / 65536.0 * 256.0
                ov = float((h >> np.uint64(32)) & np.uint64(0xFFFF)) / 65536.0 * 256.0
                u = x[k] * px_per_um
                v = y[k] * px_per_um
                if d8 & 1:  # mirror
                    u = -u
                if d8 & 2:  # transpose
                    u, v = v, u
                if d8 & 4:  # half turn
                    u, v = -u, -v
                f0 = _lookup(tiles[l0, var], u + ou, v + ov)
                f1 = _lookup(tiles[l1, var], u + ou, v + ov)
                acc += w * (f0 + (f1 - f0) * tl)
                wsum += w
        out[k] = acc / wsum


def field(seed: int, x_um, y_um, feature_um: float, coverage=0.5, cell_features: float = 12.0,
          sharp: float = 6.0) -> np.ndarray:
    """A phase-separation field at world (x, y) um whose > 0 region covers `coverage` (a
    scalar or per pixel) with features `feature_um` apart: the signed distance (tile pixels)
    to the region's edge. Up to half coverage the shapes are droplets merging into worms;
    above, the labyrinth dilates and its channels thin. Cells `cell_features` features
    across each use their own tile and orientation."""
    tiles, cov = phase_tiles()
    x = np.ascontiguousarray(x_um, np.float64).ravel()
    y = np.ascontiguousarray(y_um, np.float64).ravel()
    shape = np.shape(x_um)
    c = np.broadcast_to(np.asarray(coverage, np.float64), shape).ravel()
    level, offset = _level_offset(np.clip(c, 1e-4, 1.0 - 1e-4))
    out = np.empty(x.size, np.float64)
    if x.size == 0:
        return out.reshape(shape)
    px_per_um = period_px_cached() / float(feature_um)
    cells_per_um = 1.0 / (cell_features * float(feature_um))
    sd = np.uint64(int(seed) & 0xFFFFFFFFFFFFFFFF)
    if AVAILABLE:
        _field_nb(x, y, np.ascontiguousarray(level), out, tiles, sd, px_per_um, cells_per_um, float(sharp))
    else:  # pragma: no cover
        _field_nb(x, y, level, out, tiles, sd, px_per_um, cells_per_um, float(sharp))
    return (out + offset).reshape(shape)


@functools.lru_cache(maxsize=1)
def period_px_cached() -> float:
    return period_px()


# ------------------------------------------------------------------ periodic tiles
@_njit(parallel=True)
def _periodic_nb(stack, fu, fv, out):
    k, n = stack.shape[0], stack.shape[1]
    for p in _prange(fu.size):
        u = fu[p] * n - 0.5
        v = fv[p] * n - 0.5
        a = math.floor(u)
        b = math.floor(v)
        tu = u - a
        tv = v - b
        i0 = int(a) % n
        j0 = int(b) % n
        i1 = (i0 + 1) % n
        j1 = (j0 + 1) % n
        for c in range(k):
            top = stack[c, j0, i0] + (stack[c, j0, i1] - stack[c, j0, i0]) * tu
            bot = stack[c, j1, i0] + (stack[c, j1, i1] - stack[c, j1, i0]) * tu
            out[c, p] = top + (bot - top) * tv


def sample_periodic(stack: np.ndarray, fu, fv) -> np.ndarray:
    """Bilinear, periodic lookup of a (k, n, n) stack of tiles at fractional tile coordinates
    (fu, fv) (1 = one period): (k, ...) float32."""
    shape = np.shape(fu)
    fu = np.ascontiguousarray(fu, np.float64).ravel()
    fv = np.ascontiguousarray(fv, np.float64).ravel()
    out = np.empty((stack.shape[0], fu.size), np.float32)
    _periodic_nb(np.ascontiguousarray(stack, np.float32), fu, fv, out)
    return out.reshape((stack.shape[0],) + shape)


if __name__ == "__main__":  # regenerate the shipped tiles
    save_phase_tiles(generate_phase_tiles())
    print("wrote", PACKAGED)
